name: Update package
description: Build and push a new package when a tag has been pushed.

inputs:
  context:
    description: Path or URL pointing to a set of files.
    default: '.'
  file:
    description: Name of the Containerfile(Dockerfile).
    default: 'auto'
  platforms:
    description: Comma-separated list of platform architectures.
    required: true
  registry:
    description: Name of the package registry.
    required: true
  registry_path:
    description: Path on the registry where to push the package.
    required: true
  registry_username:
    description: Username for the package registry.
    required: true
  registry_password:
    description: Password for the package registry.
    required: true
  tags:
    description: List of tags.
    required: true
  enable_short_sha:
    description: Enable the short sha package tag.
    default: 'true'
  enable_version_tag:
    description: Enable the semver package tag.
    default: 'true'
  enable_latest_tag:
    description: Enable the latest package tag.
    default: 'true'

runs:
  using: composite
  steps:
    - id: check-version-tag
      name: Check version tag
      uses: nedix/actions/update-package/01-check-version-tag@main
      continue-on-error: true

    - if: steps.check-version-tag.outcome == 'success'
      id: update-package
      name: Update package
      uses: nedix/actions/update-package/02-update-package@main
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        platforms: ${{ inputs.platforms }}
        registry: ${{ inputs.registry }}
        registry_path: ${{ inputs.registry_path }}
        registry_username: ${{ inputs.registry_username }}
        registry_password: ${{ inputs.registry_password }}
        tags: ${{ inputs.tags }}

    - if: inputs.registry == 'docker.io'
      id: update-docker-hub-information
      name: Update Docker Hub information
      uses: peter-evans/dockerhub-description@v4
      with:
        repository: ${{ inputs.registry_path }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}
        enable-url-completion: true
        short-description: ${{ github.event.repository.description }}
