name: Update package
description: Build and push a new package when a tag has been pushed.

inputs:
  platforms:
    description: Create package for these platforms.
    required: true
  registry:
    description: Name of the package registry.
    required: true
  registry_path:
    description: Path on the registry to store the package.
    required: true
  registry_username:
    description: Username for the package registry.
    required: true
  registry_password:
    description: Password for the package registry.
    required: true
  tags:
    description: List of tags separated by newline characters.

runs:
  using: composite
  steps:
    - id: check-version-tag
      name: Check version tag
      uses: nedix/actions/update-package/01-check-version-tag@main
      continue-on-error: true

    - if: steps.check-version-tag.outcome == 'success'
      id: update-package
      name: Update package
      uses: nedix/actions/update-package/02-update-package@main
      with:
        platforms: ${{ inputs.platforms }}
        registry: ${{ inputs.registry }}
        registry_path: ${{ inputs.registry_path }}
        registry_username: ${{ inputs.registry_username }}
        registry_password: ${{ inputs.registry_password }}
        tags: ${{ inputs.tags }}
