name: Run checks

runs:
  using: composite
  steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v4.2.0
      with:
        ref: ${{ github.event.repository.default_branch }}
        fetch-depth: 0

    - id: check-version-tag
      name: Check version tag
      shell: sh
      run: |
        if git tag --points-at HEAD | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]*)?'; then
          exit 0
        fi
        echo "ERROR: There needs to be a semver version tag."
        exit 1
