name: Activate workflows
description: Activate supplied workflows.

inputs:
  token:
    description: GitHub token.
    required: true
  workflows:
    description: JSON list of workflows.
    required: true

runs:
  using: composite
  steps:
    - id: activate-workflows
      name: Activate workflows
      shell: sh
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        for WORKFLOW_NAME in $(echo '${{ inputs.workflows }}' | jq -r '.[].name'); do
          echo "Enabling workflow: ${WORKFLOW_NAME}"
          gh workflow enable "$WORKFLOW_NAME"
        done
