name: Generate app token
description: Generate the GitHub app token that will be used to update the dependencies.

inputs:
  app_id:
    description: GitHub app id.
    required: true
  app_pem:
    description: GitHub app pem.
    required: true

outputs:
  token:
    description: The GitHub app token that will be used to update the dependencies.
    value: ${{ steps.generate-app-token.outputs.token }}

runs:
  using: composite
  steps:
    - id: generate-app-token
      name: Generate GitHub app token
      uses: tibdex/github-app-token@v1.9.0
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.app_pem }}
        repositories: ${{ toJSON(github.repository) }}
