jobs:
  update-package:
    name: Update package
    runs-on: ubuntu-latest
    needs:
      - run-checks
    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${{ github.event.repository.default_branch }}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare tags
        id: tags
        run: |
          echo "DIGEST=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT
          echo "REF_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          cache-from: |
            type=registry,ref=${{ format('ghcr.io/{0}:{1}', github.repository, 'cache') }}
          cache-to: |
            type=registry,ref=${{ format('ghcr.io/{0}:{1}', github.repository, 'cache') }},mode=max
          push: true
          tags: |
            ${{ format('ghcr.io/{0}:{1}', github.repository, steps.tags.outputs.DIGEST) }}
            ${{ format('ghcr.io/{0}:{1}', github.repository, steps.tags.outputs.REF_NAME) }}
            ${{ format('ghcr.io/{0}:{1}', github.repository, 'latest') }}
