jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs:
      - run-checks
    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}
          fetch-depth: 0

      - name: Merge
        run: gh pr merge ${{ steps.extract-ref.outputs.ref }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Renovate conflicts
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run Renovate
