jobs:
  push-tag:
    name: Push tag
    runs-on: ubuntu-latest
    needs:
      - merge
    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${{ github.event.repository.default_branch }}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}
          fetch-depth: 0

      - name: Bump version
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
