name: Renovate
description: Perform automatic dependency updates.

inputs:
  token:
    description: GitHub app token.
    required: true

runs:
  using: composite
  steps:
    - id: skip-duplicate-actions
      name: Skip duplicate actions
      uses: fkirc/skip-duplicate-actions@v5.3.1
      with:
        concurrent_skipping: same_content_newer
        do_not_skip:
        skip_after_successful_duplicate: false
      continue-on-error: true

    - if: steps.skip-duplicate-actions.outputs.should-skip != 'true'
      id: renovate-dependencies
      name: Renovate dependencies
      uses: renovatebot/github-action@v40.2.7
      env:
        LOG_LEVEL: debug
        RENOVATE_AUTODISCOVER: true
        RENOVATE_AUTODISCOVER_FILTER: ${{ github.event.repository.full_name }}
        RENOVATE_AUTOMERGE: true
        RENOVATE_PLATFORM: github
        RENOVATE_PR_HOURLY_LIMIT: 0
      with:
        renovate-version: 38.59.2
        token: ${{ inputs.token }}
