name: Update dependencies
description: Update dependencies with Renovate.

inputs:
  app_id:
    description: GitHub app id.
    required: false
  app_pem:
    description: GitHub app PEM.
    required: false
  personal_access_token:
    description: GitHub access token.
    required: false

runs:
  using: composite
  steps:
    - id: prepare-token
      name: Prepare token
      uses: nedix/actions/update-dependencies/01-prepare-token@main
      with:
        app_id: ${{ inputs.app_id }}
        app_pem: ${{ inputs.app_pem }}
        personal_access_token: ${{ inputs.personal_access_token }}
      continue-on-error: true

    - if: | 
        steps.prepare-token.outputs.token != ''
        && (
            contains(fromJSON('["schedule", "workflow_dispatch"]'), github.event_name)
            || github.event.pull_request.merged == true
        )
      id: renovate
      name: Renovate
      uses: nedix/actions/update-dependencies/02-renovate@main
      with:
        token: ${{ steps.prepare-token.outputs.token }}

    - if: |
        steps.prepare-token.outputs.token != ''
        && github.event.pull_request.merged == true
        && steps.renovate.outputs.made_changes == 'false'
      id: update-version
      name: Update version
      uses: nedix/actions/update-dependencies/03-update-version@main
      with:
        token: ${{ steps.prepare-token.outputs.token }}
