name: Update dependencies
description: Update dependencies with Renovate.

inputs:
  app_id:
    description: GitHub app id.
    default: 'false'
  app_pem:
    description: GitHub app PEM.
    default: 'false'
  personal_access_token:
    description: GitHub access token.
    default: 'false'

runs:
  using: composite
  steps:
    - id: generate-token
      name: Generate token
      uses: nedix/actions/update-dependencies/01-generate-token@main
      with:
        personal_access_token: ${{ inputs.personal_access_token }}
        app_id: ${{ inputs.app_id }}
        app_pem: ${{ inputs.app_pem }}
      continue-on-error: true

    - if: | 
        steps.generate-token.outcome == 'success'
        && (
            contains(fromJSON('["schedule", "workflow_dispatch"]'), github.event_name)
            || github.event.pull_request.merged == true
        )
      id: renovate
      name: Renovate
      uses: nedix/actions/update-dependencies/02-renovate@main
      with:
        token: ${{ steps.generate-token.outputs.token }}

    - if: |
        steps.generate-token.outcome == 'success'
        && github.event.pull_request.merged == true
        && steps.renovate.outputs.made_changes == 'false'
      id: update-version
      name: Update version
      uses: nedix/actions/update-dependencies/03-update-version@main
      with:
        token: ${{ steps.generate-token.outputs.token }}
