name: Update dependencies
description: Update dependencies with Renovate.

inputs:
  enable_scheduled_updates:
    description: Set value to `true` to enable scheduled updates.
    default: 'false'

runs:
  using: composite
  steps:
    - id: check-skip-schedule
      env:
        SCHEDULED_UPDATE: ${{ github.event_name == 'schedule' }}
        SCHEDULED_UPDATES_ENABLED: ${{ inputs.enable_scheduled_updates }}
      shell: sh
      run: |
        if [ "$SCHEDULED_UPDATE" = "true" ] && [ -z "$SCHEDULED_UPDATES_ENABLED" ]; then
          echo "should-skip-schedule=true" >> "$GITHUB_OUTPUT"
        else
          echo "should-skip-schedule=false" >> "$GITHUB_OUTPUT"
        fi    

    - id: generate-app-token
      shell: sh
      run: |
        echo "token=${{ github.token }}" >> "$GITHUB_OUTPUT"

    - if: |
        steps.check-skip-schedule.outputs.should-skip-schedule == 'false'
        && contains(fromJSON('["schedule", "workflow_dispatch"]'), github.event_name)
        || github.event.pull_request.merged == true
      id: renovate
      name: Renovate
      uses: nedix/actions/update-dependencies/01-renovate@main
      with:
        token: ${{ steps.generate-app-token.outputs.token }}

    - if: |
        github.event.pull_request.merged == true
        && steps.renovate.outputs.made_changes == 'false'
      id: update-version
      name: Update version
      uses: nedix/actions/update-dependencies/02-update-version@main
      with:
        token: ${{ steps.generate-app-token.outputs.token }}
