name: Update dependencies
description: Update dependencies with Renovate.

runs:
  using: composite
  steps:
    - id: generate-app-token
      shell: sh
      run: echo "token=${{ github.token }}" >> "$GITHUB_OUTPUT"

    - if: |
        contains(fromJSON('["schedule", "workflow_dispatch"]'), github.event_name)
        || github.event.pull_request.merged == true
      id: renovate
      name: Renovate
      uses: nedix/actions/update-dependencies/01-renovate@main
      with:
        token: ${{ steps.generate-app-token.outputs.token }}

    - if: |
        github.event.pull_request.merged == true
        && steps.renovate.outputs.made_changes == 'false'
      id: update-version
      name: Update version
      uses: nedix/actions/update-dependencies/02-update-version@main
      with:
        token: ${{ steps.generate-app-token.outputs.token }}
