name: Run checks
description: '# TODO'

inputs:
  command:
    description: Runs a test command.
    required: true

runs:
  using: composite
  steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v6.0.2
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        fetch-depth: 0

    - id: run-test-command
      name: Run test command
      shell: sh
      run: |
        set -e
        ${{ inputs.command }}
