name: Increment version
description: Increment the version tag.

inputs:
  token:
    description: GitHub app token.
    required: true

runs:
  using: composite
  steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v4.2.0
      with:
        ref: ${{ github.event.repository.default_branch }}
        fetch-depth: 0

    - id: bump-version
      name: Bump version
      uses: anothrNick/github-tag-action@1.71.0
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        WITH_V: true
