name: Update package

inputs:
  platforms:
    description: Create package for these platforms.
    required: true
  registry:
    description: Url for the package registry.
    required: true
  registry_username:
    description: Username for the package registry
    required: true
  registry_password:
    description: Password for the package registry
    required: true
  tags:
    description: Collection of tags separated by newlines.
    required: true

runs:
  using: composite
  steps:
    - id: registry-login
      name: Login to package registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - id: setup-qemu
      name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - id: setup-buildx
      name: Setup Buildx
      uses: docker/setup-buildx-action@v3

    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v4.2.0
      with:
        fetch-depth: 0
        ref: ${{ github.event.repository.default_branch }}

    - id: build-and-push
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: ${{ inputs.platforms }}
        push: true
        tags: ${{ inputs.tags }}

# TODO: package cache
#        cache-from: |
#          type=registry,ref=${{ format('ghcr.io/{0}:{1}', github.repository, 'cache') }}
#        cache-to: |
#          type=registry,ref=${{ format('ghcr.io/{0}:{1}', github.repository, 'cache') }},mode=max
