name: Update package

inputs:
  context:
    description: Path pointing to a set of files.
    default: '.'
  file:
    description: Name of the Containerfile(Dockerfile).
    default: 'auto'
  platforms:
    description: Comma-separated list of platform architectures.
    required: true
  registry:
    description: Name of the package registry.
    required: true
  registry_path:
    description: Path on the registry where to push the package.
    required: true
  registry_username:
    description: Username for the package registry
    required: true
  registry_password:
    description: Password for the package registry
    required: true
  tags:
    description: List of tags.
    required: true
  enable_short_sha:
    description: Enable the short sha package tag.
    default: 'true'
  enable_version_tag:
    description: Enable the semver package tag.
    default: 'true'
  enable_latest_tag:
    description: Enable the latest package tag.
    default: 'true'

runs:
  using: composite
  steps:
    - id: registry-login
      name: Login to package registry
      uses: docker/login-action@v3.4.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - id: cache-registry-login
      name: Login to cache package registry
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - id: setup-qemu
      name: Setup QEMU
      uses: docker/setup-qemu-action@v3.6.0

    - id: setup-buildx
      name: Setup Buildx
      uses: docker/setup-buildx-action@v3.11.1

    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
        ref: ${{ github.event.repository.default_branch }}

    - id: prepare-tags
      name: Prepare tags
      shell: sh
      run: |
        echo "short_sha=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT
        echo "version_tag=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT

    - if: inputs.file == 'auto'
      id: find-containerfile
      name: Find containerfile
      shell: sh
      run: |
        cd "${{ inputs.context }}"
        test -f Containerfile && echo "file=Containerfile" >> $GITHUB_OUTPUT && exit 0
        test -f Dockerfile && echo "file=Dockerfile" >> $GITHUB_OUTPUT && exit 0
        echo "Failed to find a containerfile within the given context path." && echo "file=none" >> $GITHUB_OUTPUT

    - if: inputs.file != 'auto' || steps.find-containerfile.outputs.file != 'none'
      id: build-and-push
      name: Build and push
      uses: docker/build-push-action@v6.18.0
      with:
        cache-from: |
          type=registry,ref=${{ format('{0}/{1}:{2}', 'ghcr.io', github.repository, 'cache') }}
        cache-to: |
          type=registry,ref=${{ format('{0}/{1}:{2}', 'ghcr.io', github.repository, 'cache') }},mode=max
        context: ${{ inputs.context }}
        file: ${{ inputs.file == 'auto' && steps.find-containerfile.outputs.file || inputs.file }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: |
          ${{ inputs.enable_latest_tag == 'true' && format('{0}/{1}:{2}', inputs.registry, inputs.registry_path, 'latest') }}
          ${{ inputs.enable_short_sha == 'true' && format('{0}/{1}:{2}', inputs.registry, inputs.registry_path, steps.prepare-tags.outputs.short_sha) }}
          ${{ inputs.enable_version_tag == 'true' && format('{0}/{1}:{2}', inputs.registry, inputs.registry_path, steps.prepare-tags.outputs.version_tag) }}
          ${{ inputs.tags }}

    - if: steps.build-and-push.conclusion == 'success'
      id: extract-sbom
      name: Extract SBOM
      uses: docker/scout-action@v1.18.1
      with:
        command: cves,sbom
        format: spdx
        image: "${{ format('{0}/{1}@{2}', inputs.registry, inputs.registry_path, steps.build-and-push.outputs.digest) }}"
        output: sbom.spdx.json
        sarif-file: sarif.output.json

    - if: steps.extract-sbom.conclusion == 'success'
      id: attest-sbom
      name: Attest SBOM
      uses: actions/attest-sbom@v2.4.0
      with:
        sbom-path: sbom.spdx.json
        subject-path: ${{ github.workspace }}
      continue-on-error: true

    - if: steps.extract-sbom.conclusion == 'success'
      id: upload-sarif
      name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3.29.1
      with:
        sarif_file: sarif.output.json
      continue-on-error: true
