name: Update package

on:
  push:
    tags: ['*']

permissions:
  attestations: write
  id-token: write
  packages: write
  security-events: write

jobs:
  update-package:
    name: Update package
    runs-on: ubuntu-latest
    steps:
      - id: update-package
        name: Update package
        uses: nedix/actions/update-package@main
        env:
          registry_secret: ${{ secrets.REGISTRY_DOMAIN }}
          registry_path_secret: ${{ secrets.REGISTRY_PATH }}
          registry_username_secret: ${{ secrets.REGISTRY_USERNAME }}
          registry_password_secret: ${{ secrets.REGISTRY_PASSWORD }}
        with:
          platforms: 'linux/amd64,linux/arm64/v8'
          registry: ${{ env.registry_secret || 'ghcr.io' }}
          registry_path: ${{ env.registry_path_secret || github.repository }}
          registry_username: ${{ env.registry_username_secret || github.actor }}
          registry_password: ${{ env.registry_password_secret || github.token }}
