name: Update dependencies

on:
  merge_group:
  pull_request_target:
    branches: ['main']
    paths-ignore: ['.github/**/*']
    types: ['closed']
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

env:
  SCHEDULED_UPDATES_ENABLED: 'false'

jobs:
  update-dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - id: update-dependencies
        name: Update dependencies
        uses: nedix/actions/update-dependencies@main
        with:
          scheduled_updates_enabled: ${{ envs.SCHEDULED_UPDATES_ENABLED }}
